# Generated by Django 2.2.16 on 2020-10-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201018_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '問い合わせ', 'verbose_name_plural': '問い合わせ'},
        ),
        migrations.AlterModelOptions(
            name='casetype',
            options={'verbose_name': '問い合わせ分類', 'verbose_name_plural': '問い合わせ分類'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '商品情報', 'verbose_name_plural': '商品情報'},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name': '装置分類', 'verbose_name_plural': '装置分類'},
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('作成中', '作成中'), ('承認待ち', '承認待ち'), ('承認済み', '承認済み'), ('商談中', '商談中'), ('取り下げ', '取り下げ')], default='作成中', max_length=20, verbose_name='ステータス'),
        ),
    ]
