# Generated by Django 2.2.16 on 2020-10-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201018_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image01',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像01'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('作成中', '作成中'), ('承認待ち', '承認待ち'), ('承認済み', '承認済み'), ('商談中', '商談中'), ('成約済み', '成約済み'), ('取り下げ', '取り下げ')], default='作成中', max_length=20, verbose_name='ステータス'),
        ),
    ]
