# Generated by Django 2.2.16 on 2020-10-25 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201018_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='company_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='会社住所'),
        ),
        migrations.AddField(
            model_name='case',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='会社名'),
        ),
        migrations.AddField(
            model_name='case',
            name='tel_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='携帯電話番号はハイフンなしで入力してください', regex='^[0-9]+$')], verbose_name='携帯電話番号'),
        ),
    ]
