# Generated by Django 2.2.16 on 2020-10-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20201025_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='item_list',
            field=models.ManyToManyField(blank=True, related_name='item_list', to='web.Item', verbose_name='問い合わせ商品'),
        ),
    ]
