# Generated by Django 2.2.16 on 2020-10-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_case_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Item', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='case',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
    ]
