# Generated by Django 2.2.16 on 2020-10-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20201025_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image02',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像02'),
        ),
        migrations.AddField(
            model_name='item',
            name='image03',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像03'),
        ),
        migrations.AddField(
            model_name='item',
            name='image04',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像04'),
        ),
        migrations.AddField(
            model_name='item',
            name='image05',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像05'),
        ),
    ]
