# Generated by Django 2.2.16 on 2020-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20201103_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('確認中', '確認中'), ('対応中', '対応中'), ('クローズ', 'クローズ')], default='確認中', max_length=255, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='case',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='問い合わせ詳細'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
