name: django unit test

on: 
  pull_request:
    branches: [develop]
#   push:
#     branches: [ local_furuya ]


jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Django app test
      run: python manage.py test --settings=mune.githubactions_settings --keepdb
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SENDGRID_API_KEY: a
